name: Notify WaspLib2 of new release.

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch in target repo
        env:
          TARGET_REPO: Torwent/WaspLib2
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            https://api.github.com/repos/$TARGET_REPO/dispatches \
            -d "{\"event_type\": \"release-published\", \"client_payload\": {\"tag_name\": \"$TAG_NAME\"}}"
